# for local development
version: "3.7"
services:
  validation:
    image: dscribe/basic-node
    build:
      context: .
      target: base
    volumes:
      - ".:/app"
    tty: true
    stdin_open: true
